# Generated by Django 6.0.6 on 2026-06-12 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('grade', models.CharField(choices=[('I', '1st'), ('II', '2nd'), ('III', '3rd'), ('IV', '4th'), ('V', '5th'), ('VI', '6th'), ('VII', '7th'), ('VIII', '8th'), ('IX', '9th'), ('X', '10th'), ('XI', '11th'), ('XII', '12th')], max_length=8)),
                ('school_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('nationality', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussion.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('qualification', models.CharField(max_length=30)),
                ('years_of_exp', models.SmallIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('nationality', models.CharField(max_length=30)),
                ('sub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussion.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussion.student')),
                ('sub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussion.subject')),
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussion.teacher')),
            ],
        ),
    ]
