# Generated by Django 6.0.6 on 2026-06-15 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sub_id',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='sub_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='sub_id',
            new_name='subject',
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussion.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussion.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussion.post')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussion.teacher')),
            ],
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
